//define_mac.h
#define WRITEBYTE(WORD,BYTESSTARTBITPOS,VAL)\
		WORD=((WORD & ~(0XFF << BYTESSTARTBITPOS)) | (((unsigned)VAL << BYTESSTARTBITPOS))) 

#define SETBIT(WORD,BITPOS) WORD|=1<<BITPOS

#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT)\
		DWORD=((DWORD &~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))

#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)

#define WRITEBIT(WORD,BITPOS,BITLEVEL)\
		(BITLEVEL ? (WORD|=1<<BITPOS) : (WORD &=~(1<<BITPOS)))
		//WORD=((WORD &~(1<<BITPOS)) | (BITLEVEL <<BITPOS))

#define WRITE2PORTBIT(PORTNO,BITPOS,BITLEVEL)\
		((PORTNO==0)?\
			(BITLEVEL ? (IOSET0=1<<BITPOS) : (IOCLR0=1<<BITPOS)): \
			(BITLEVEL ? (IOSET1=1<<BITPOS) : (IOCLR1=1<<BITPOS)))

#define WRITENIBBLE(WORD,NIBBLESTARTPOS,VAL)  WORD=((WORD &~(15<<NIBBLESTARTPOS))|((VAL<<NIBBLESTARTPOS)))

#define READNIBBLE(WORD,NIBBLESTARTBIT)  ((WORD>>NIBBLESTARTBIT)&15)
		

